/**
 * Database Types for Halcyon Cinema + StoryForge
 * Auto-generated types should replace this file using:
 * npm run db:generate-types
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Enum types
export type ProjectMode = 'storyforge' | 'cinema';
export type SubscriptionTier = 'free' | 'pro' | 'studio' | 'enterprise';
export type CanonEntityType = 'character' | 'location' | 'rule' | 'event' | 'theme' | 'reference' | 'item' | 'relationship';
export type CanonLockStatus = 'unlocked' | 'soft_locked' | 'hard_locked';
export type ContentStatus = 'draft' | 'review' | 'final' | 'archived';
export type ShotType = 'establishing' | 'wide' | 'medium' | 'close_up' | 'extreme_close_up' | 'over_shoulder' | 'pov' | 'aerial' | 'tracking' | 'dolly' | 'pan' | 'tilt' | 'zoom' | 'static';
export type ProductionFormat = 'film' | 'tv' | 'animation' | 'game' | 'web_series' | 'short';
export type ExportFormat = 'docx' | 'pdf' | 'epub' | 'fountain' | 'markdown' | 'json';
export type ConflictResolution = 'keep_canon' | 'update_canon' | 'fork_timeline';

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          display_name: string | null;
          avatar_url: string | null;
          subscription_tier: SubscriptionTier;
          subscription_status: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          trial_ends_at: string | null;
          monthly_ai_tokens_used: number;
          monthly_ai_tokens_limit: number;
          monthly_exports_used: number;
          monthly_exports_limit: number;
          legacy_user: boolean;
          legacy_import_date: string | null;
          preferred_mode: ProjectMode;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          display_name?: string | null;
          avatar_url?: string | null;
          subscription_tier?: SubscriptionTier;
          subscription_status?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          trial_ends_at?: string | null;
          monthly_ai_tokens_used?: number;
          monthly_ai_tokens_limit?: number;
          monthly_exports_used?: number;
          monthly_exports_limit?: number;
          legacy_user?: boolean;
          legacy_import_date?: string | null;
          preferred_mode?: ProjectMode;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          subscription_tier?: SubscriptionTier;
          subscription_status?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          trial_ends_at?: string | null;
          monthly_ai_tokens_used?: number;
          monthly_ai_tokens_limit?: number;
          monthly_exports_used?: number;
          monthly_exports_limit?: number;
          legacy_user?: boolean;
          legacy_import_date?: string | null;
          preferred_mode?: ProjectMode;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          subtitle: string | null;
          description: string | null;
          genre: string | null;
          logline: string | null;
          mode: ProjectMode;
          cinema_enabled_at: string | null;
          word_count: number;
          chapter_count: number;
          scene_count: number;
          target_word_count: number | null;
          production_format: ProductionFormat;
          status: ContentStatus;
          is_demo: boolean;
          is_archived: boolean;
          legacy_project: boolean;
          legacy_source: string | null;
          legacy_id: string | null;
          cover_image_url: string | null;
          color_scheme: Json;
          settings: Json;
          created_at: string;
          updated_at: string;
          last_edited_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          subtitle?: string | null;
          description?: string | null;
          genre?: string | null;
          logline?: string | null;
          mode?: ProjectMode;
          cinema_enabled_at?: string | null;
          word_count?: number;
          chapter_count?: number;
          scene_count?: number;
          target_word_count?: number | null;
          production_format?: ProductionFormat;
          status?: ContentStatus;
          is_demo?: boolean;
          is_archived?: boolean;
          legacy_project?: boolean;
          legacy_source?: string | null;
          legacy_id?: string | null;
          cover_image_url?: string | null;
          color_scheme?: Json;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
          last_edited_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          subtitle?: string | null;
          description?: string | null;
          genre?: string | null;
          logline?: string | null;
          mode?: ProjectMode;
          cinema_enabled_at?: string | null;
          word_count?: number;
          chapter_count?: number;
          scene_count?: number;
          target_word_count?: number | null;
          production_format?: ProductionFormat;
          status?: ContentStatus;
          is_demo?: boolean;
          is_archived?: boolean;
          legacy_project?: boolean;
          legacy_source?: string | null;
          legacy_id?: string | null;
          cover_image_url?: string | null;
          color_scheme?: Json;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
          last_edited_at?: string;
        };
      };
      chapters: {
        Row: {
          id: string;
          project_id: string;
          title: string;
          summary: string | null;
          content: string;
          order_index: number;
          word_count: number;
          status: ContentStatus;
          ai_generated_percentage: number;
          last_ai_action: string | null;
          last_ai_action_at: string | null;
          version: number;
          author_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          title: string;
          summary?: string | null;
          content?: string;
          order_index: number;
          word_count?: number;
          status?: ContentStatus;
          ai_generated_percentage?: number;
          last_ai_action?: string | null;
          last_ai_action_at?: string | null;
          version?: number;
          author_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          title?: string;
          summary?: string | null;
          content?: string;
          order_index?: number;
          word_count?: number;
          status?: ContentStatus;
          ai_generated_percentage?: number;
          last_ai_action?: string | null;
          last_ai_action_at?: string | null;
          version?: number;
          author_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      scenes: {
        Row: {
          id: string;
          chapter_id: string;
          project_id: string;
          title: string | null;
          content: string;
          order_index: number;
          location: string | null;
          time_of_day: string | null;
          semantic_data: Json;
          character_ids: string[];
          location_id: string | null;
          status: ContentStatus;
          word_count: number;
          shot_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          chapter_id: string;
          project_id: string;
          title?: string | null;
          content?: string;
          order_index: number;
          location?: string | null;
          time_of_day?: string | null;
          semantic_data?: Json;
          character_ids?: string[];
          location_id?: string | null;
          status?: ContentStatus;
          word_count?: number;
          shot_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          chapter_id?: string;
          project_id?: string;
          title?: string | null;
          content?: string;
          order_index?: number;
          location?: string | null;
          time_of_day?: string | null;
          semantic_data?: Json;
          character_ids?: string[];
          location_id?: string | null;
          status?: ContentStatus;
          word_count?: number;
          shot_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      canon_entries: {
        Row: {
          id: string;
          project_id: string;
          entity_type: CanonEntityType;
          name: string;
          slug: string;
          description: string | null;
          data: Json;
          lock_status: CanonLockStatus;
          locked_at: string | null;
          locked_by: string | null;
          version: number;
          parent_id: string | null;
          related_entry_ids: string[];
          reference_count: number;
          last_referenced_at: string | null;
          timeline_id: string | null;
          is_active: boolean;
          search_vector: unknown | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          entity_type: CanonEntityType;
          name: string;
          slug: string;
          description?: string | null;
          data?: Json;
          lock_status?: CanonLockStatus;
          locked_at?: string | null;
          locked_by?: string | null;
          version?: number;
          parent_id?: string | null;
          related_entry_ids?: string[];
          reference_count?: number;
          last_referenced_at?: string | null;
          timeline_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          entity_type?: CanonEntityType;
          name?: string;
          slug?: string;
          description?: string | null;
          data?: Json;
          lock_status?: CanonLockStatus;
          locked_at?: string | null;
          locked_by?: string | null;
          version?: number;
          parent_id?: string | null;
          related_entry_ids?: string[];
          reference_count?: number;
          last_referenced_at?: string | null;
          timeline_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      canon_characters: {
        Row: {
          id: string;
          canon_entry_id: string;
          project_id: string;
          name: string;
          full_name: string | null;
          aliases: string[];
          age: string | null;
          gender: string | null;
          appearance: string | null;
          personality: string | null;
          motivations: string | null;
          fears: string | null;
          strengths: string[];
          weaknesses: string[];
          backstory: string | null;
          occupation: string | null;
          role: string | null;
          relationships: Json;
          speech_patterns: string | null;
          vocabulary_level: string | null;
          catchphrases: string[];
          character_arc: string | null;
          visual_description: string | null;
          reference_images: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          canon_entry_id: string;
          project_id: string;
          name: string;
          full_name?: string | null;
          aliases?: string[];
          age?: string | null;
          gender?: string | null;
          appearance?: string | null;
          personality?: string | null;
          motivations?: string | null;
          fears?: string | null;
          strengths?: string[];
          weaknesses?: string[];
          backstory?: string | null;
          occupation?: string | null;
          role?: string | null;
          relationships?: Json;
          speech_patterns?: string | null;
          vocabulary_level?: string | null;
          catchphrases?: string[];
          character_arc?: string | null;
          visual_description?: string | null;
          reference_images?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          canon_entry_id?: string;
          project_id?: string;
          name?: string;
          full_name?: string | null;
          aliases?: string[];
          age?: string | null;
          gender?: string | null;
          appearance?: string | null;
          personality?: string | null;
          motivations?: string | null;
          fears?: string | null;
          strengths?: string[];
          weaknesses?: string[];
          backstory?: string | null;
          occupation?: string | null;
          role?: string | null;
          relationships?: Json;
          speech_patterns?: string | null;
          vocabulary_level?: string | null;
          catchphrases?: string[];
          character_arc?: string | null;
          visual_description?: string | null;
          reference_images?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      canon_locations: {
        Row: {
          id: string;
          canon_entry_id: string;
          project_id: string;
          name: string;
          type: string | null;
          category: string | null;
          description: string | null;
          atmosphere: string | null;
          sensory_details: Json;
          parent_location_id: string | null;
          coordinates: Json | null;
          history: string | null;
          significance: string | null;
          visual_description: string | null;
          reference_images: string[];
          lighting_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          canon_entry_id: string;
          project_id: string;
          name: string;
          type?: string | null;
          category?: string | null;
          description?: string | null;
          atmosphere?: string | null;
          sensory_details?: Json;
          parent_location_id?: string | null;
          coordinates?: Json | null;
          history?: string | null;
          significance?: string | null;
          visual_description?: string | null;
          reference_images?: string[];
          lighting_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          canon_entry_id?: string;
          project_id?: string;
          name?: string;
          type?: string | null;
          category?: string | null;
          description?: string | null;
          atmosphere?: string | null;
          sensory_details?: Json;
          parent_location_id?: string | null;
          coordinates?: Json | null;
          history?: string | null;
          significance?: string | null;
          visual_description?: string | null;
          reference_images?: string[];
          lighting_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      canon_rules: {
        Row: {
          id: string;
          canon_entry_id: string;
          project_id: string;
          name: string;
          category: string | null;
          description: string;
          constraints: string[];
          enables: string[];
          exceptions: string[];
          priority: number;
          enforcement_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          canon_entry_id: string;
          project_id: string;
          name: string;
          category?: string | null;
          description: string;
          constraints?: string[];
          enables?: string[];
          exceptions?: string[];
          priority?: number;
          enforcement_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          canon_entry_id?: string;
          project_id?: string;
          name?: string;
          category?: string | null;
          description?: string;
          constraints?: string[];
          enables?: string[];
          exceptions?: string[];
          priority?: number;
          enforcement_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      canon_events: {
        Row: {
          id: string;
          canon_entry_id: string;
          project_id: string;
          name: string;
          description: string | null;
          story_date: string | null;
          relative_order: number | null;
          duration: string | null;
          consequences: string[];
          affected_character_ids: string[];
          affected_location_ids: string[];
          event_type: string | null;
          significance: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          canon_entry_id: string;
          project_id: string;
          name: string;
          description?: string | null;
          story_date?: string | null;
          relative_order?: number | null;
          duration?: string | null;
          consequences?: string[];
          affected_character_ids?: string[];
          affected_location_ids?: string[];
          event_type?: string | null;
          significance?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          canon_entry_id?: string;
          project_id?: string;
          name?: string;
          description?: string | null;
          story_date?: string | null;
          relative_order?: number | null;
          duration?: string | null;
          consequences?: string[];
          affected_character_ids?: string[];
          affected_location_ids?: string[];
          event_type?: string | null;
          significance?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      canon_themes: {
        Row: {
          id: string;
          canon_entry_id: string;
          project_id: string;
          name: string;
          description: string | null;
          how_expressed: string | null;
          symbols: string[];
          motifs: string[];
          related_character_ids: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          canon_entry_id: string;
          project_id: string;
          name: string;
          description?: string | null;
          how_expressed?: string | null;
          symbols?: string[];
          motifs?: string[];
          related_character_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          canon_entry_id?: string;
          project_id?: string;
          name?: string;
          description?: string | null;
          how_expressed?: string | null;
          symbols?: string[];
          motifs?: string[];
          related_character_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      shots: {
        Row: {
          id: string;
          scene_id: string;
          project_id: string;
          order_index: number;
          shot_type: ShotType;
          duration_seconds: number | null;
          description: string;
          composition: string | null;
          camera_movement: string | null;
          lighting: string | null;
          visual_prompt: string | null;
          prompt_template: string | null;
          character_ids: string[];
          location_id: string | null;
          mood: string | null;
          emotional_beat: string | null;
          technical_notes: string | null;
          vfx_required: boolean;
          vfx_notes: string | null;
          preview_image_url: string | null;
          mood_board_urls: string[];
          format: ProductionFormat;
          aspect_ratio: string;
          status: ContentStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          scene_id: string;
          project_id: string;
          order_index: number;
          shot_type: ShotType;
          duration_seconds?: number | null;
          description: string;
          composition?: string | null;
          camera_movement?: string | null;
          lighting?: string | null;
          visual_prompt?: string | null;
          prompt_template?: string | null;
          character_ids?: string[];
          location_id?: string | null;
          mood?: string | null;
          emotional_beat?: string | null;
          technical_notes?: string | null;
          vfx_required?: boolean;
          vfx_notes?: string | null;
          preview_image_url?: string | null;
          mood_board_urls?: string[];
          format: ProductionFormat;
          aspect_ratio?: string;
          status?: ContentStatus;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          scene_id?: string;
          project_id?: string;
          order_index?: number;
          shot_type?: ShotType;
          duration_seconds?: number | null;
          description?: string;
          composition?: string | null;
          camera_movement?: string | null;
          lighting?: string | null;
          visual_prompt?: string | null;
          prompt_template?: string | null;
          character_ids?: string[];
          location_id?: string | null;
          mood?: string | null;
          emotional_beat?: string | null;
          technical_notes?: string | null;
          vfx_required?: boolean;
          vfx_notes?: string | null;
          preview_image_url?: string | null;
          mood_board_urls?: string[];
          format?: ProductionFormat;
          aspect_ratio?: string;
          status?: ContentStatus;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_generations: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          generation_type: string;
          target_type: string | null;
          target_id: string | null;
          prompt_used: string | null;
          input_context: Json | null;
          output_content: string | null;
          canon_loaded: Json | null;
          canon_conflicts_detected: Json | null;
          canon_resolution: ConflictResolution | null;
          tokens_used: number | null;
          model_used: string | null;
          latency_ms: number | null;
          status: string;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          project_id: string;
          generation_type: string;
          target_type?: string | null;
          target_id?: string | null;
          prompt_used?: string | null;
          input_context?: Json | null;
          output_content?: string | null;
          canon_loaded?: Json | null;
          canon_conflicts_detected?: Json | null;
          canon_resolution?: ConflictResolution | null;
          tokens_used?: number | null;
          model_used?: string | null;
          latency_ms?: number | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          generation_type?: string;
          target_type?: string | null;
          target_id?: string | null;
          prompt_used?: string | null;
          input_context?: Json | null;
          output_content?: string | null;
          canon_loaded?: Json | null;
          canon_conflicts_detected?: Json | null;
          canon_resolution?: ConflictResolution | null;
          tokens_used?: number | null;
          model_used?: string | null;
          latency_ms?: number | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
      };
      exports: {
        Row: {
          id: string;
          user_id: string;
          project_id: string;
          format: ExportFormat;
          file_name: string;
          file_url: string | null;
          file_size_bytes: number | null;
          export_scope: string | null;
          chapter_ids: string[];
          options: Json;
          status: string;
          error_message: string | null;
          created_at: string;
          completed_at: string | null;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          project_id: string;
          format: ExportFormat;
          file_name: string;
          file_url?: string | null;
          file_size_bytes?: number | null;
          export_scope?: string | null;
          chapter_ids?: string[];
          options?: Json;
          status?: string;
          error_message?: string | null;
          created_at?: string;
          completed_at?: string | null;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string;
          format?: ExportFormat;
          file_name?: string;
          file_url?: string | null;
          file_size_bytes?: number | null;
          export_scope?: string | null;
          chapter_ids?: string[];
          options?: Json;
          status?: string;
          error_message?: string | null;
          created_at?: string;
          completed_at?: string | null;
          expires_at?: string | null;
        };
      };
      feature_flags: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          enabled: boolean;
          enabled_for_tiers: SubscriptionTier[];
          enabled_for_users: string[];
          rollout_percentage: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          enabled?: boolean;
          enabled_for_tiers?: SubscriptionTier[];
          enabled_for_users?: string[];
          rollout_percentage?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          enabled?: boolean;
          enabled_for_tiers?: SubscriptionTier[];
          enabled_for_users?: string[];
          rollout_percentage?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      metrics_events: {
        Row: {
          id: string;
          user_id: string | null;
          project_id: string | null;
          event_name: string;
          event_category: string | null;
          event_data: Json;
          session_id: string | null;
          page_path: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          project_id?: string | null;
          event_name: string;
          event_category?: string | null;
          event_data?: Json;
          session_id?: string | null;
          page_path?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          project_id?: string | null;
          event_name?: string;
          event_category?: string | null;
          event_data?: Json;
          session_id?: string | null;
          page_path?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
      timelines: {
        Row: {
          id: string;
          project_id: string;
          name: string;
          description: string | null;
          is_main: boolean;
          parent_timeline_id: string | null;
          fork_point_event_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          name: string;
          description?: string | null;
          is_main?: boolean;
          parent_timeline_id?: string | null;
          fork_point_event_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          name?: string;
          description?: string | null;
          is_main?: boolean;
          parent_timeline_id?: string | null;
          fork_point_event_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Functions: {
      get_user_features: {
        Args: { p_user_id: string };
        Returns: { feature_name: string; enabled: boolean }[];
      };
      can_access_cinema: {
        Args: { p_user_id: string };
        Returns: boolean;
      };
      get_project_canon_for_ai: {
        Args: { p_project_id: string };
        Returns: Json;
      };
    };
  };
}

// Convenience type aliases
export type User = Database['public']['Tables']['users']['Row'];
export type UserInsert = Database['public']['Tables']['users']['Insert'];
export type UserUpdate = Database['public']['Tables']['users']['Update'];

export type Project = Database['public']['Tables']['projects']['Row'];
export type ProjectInsert = Database['public']['Tables']['projects']['Insert'];
export type ProjectUpdate = Database['public']['Tables']['projects']['Update'];

export type Chapter = Database['public']['Tables']['chapters']['Row'];
export type ChapterInsert = Database['public']['Tables']['chapters']['Insert'];
export type ChapterUpdate = Database['public']['Tables']['chapters']['Update'];

export type Scene = Database['public']['Tables']['scenes']['Row'];
export type SceneInsert = Database['public']['Tables']['scenes']['Insert'];
export type SceneUpdate = Database['public']['Tables']['scenes']['Update'];

export type CanonEntry = Database['public']['Tables']['canon_entries']['Row'];
export type CanonEntryInsert = Database['public']['Tables']['canon_entries']['Insert'];
export type CanonEntryUpdate = Database['public']['Tables']['canon_entries']['Update'];

export type CanonCharacter = Database['public']['Tables']['canon_characters']['Row'];
export type CanonLocation = Database['public']['Tables']['canon_locations']['Row'];
export type CanonRule = Database['public']['Tables']['canon_rules']['Row'];
export type CanonEvent = Database['public']['Tables']['canon_events']['Row'];
export type CanonTheme = Database['public']['Tables']['canon_themes']['Row'];

export type Shot = Database['public']['Tables']['shots']['Row'];
export type ShotInsert = Database['public']['Tables']['shots']['Insert'];
export type ShotUpdate = Database['public']['Tables']['shots']['Update'];

export type AIGeneration = Database['public']['Tables']['ai_generations']['Row'];
export type Export = Database['public']['Tables']['exports']['Row'];
export type FeatureFlag = Database['public']['Tables']['feature_flags']['Row'];
export type MetricsEvent = Database['public']['Tables']['metrics_events']['Row'];
export type Timeline = Database['public']['Tables']['timelines']['Row'];
